# Generated by Django 4.1.13 on 2024-03-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=50, unique=True, verbose_name="项目名称"),
                ),
                (
                    "project_type",
                    models.CharField(
                        default="default", max_length=50, verbose_name="项目类型"
                    ),
                ),
                (
                    "project_code",
                    models.CharField(max_length=50, unique=True, verbose_name="项目代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="members", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(max_length=50, unique=True, verbose_name="角色名称"),
                ),
                (
                    "role_code",
                    models.CharField(max_length=50, unique=True, verbose_name="角色代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="role_members", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(max_length=50, unique=True, verbose_name="资源名称"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        default="default", max_length=50, verbose_name="资源类型"
                    ),
                ),
                (
                    "resource_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="资源IP"
                    ),
                ),
                (
                    "resource_cpu",
                    models.IntegerField(blank=True, null=True, verbose_name="资源CPU"),
                ),
                (
                    "resource_memory",
                    models.IntegerField(blank=True, null=True, verbose_name="资源内存"),
                ),
                (
                    "resource_disk",
                    models.IntegerField(blank=True, null=True, verbose_name="资源磁盘"),
                ),
                (
                    "resource_os",
                    models.CharField(blank=True, max_length=50, verbose_name="资源操作系统"),
                ),
                ("description", models.TextField(blank=True, verbose_name="资源描述")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_project",
                        to="apps.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_name",
                    models.CharField(max_length=50, unique=True, verbose_name="应用名称"),
                ),
                (
                    "application_type",
                    models.CharField(
                        default="default", max_length=50, verbose_name="应用类型"
                    ),
                ),
                (
                    "application_code",
                    models.CharField(max_length=50, unique=True, verbose_name="应用代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="应用描述")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "application_port",
                    models.IntegerField(blank=True, null=True, verbose_name="应用端口"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_project",
                        to="apps.project",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_resource",
                        to="apps.resource",
                    ),
                ),
            ],
        ),
    ]
