# Generated by Django 4.1.13 on 2024-03-22 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_project_role_resource_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "managed": True,
                "verbose_name": "应用管理",
                "verbose_name_plural": "应用管理",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "managed": True,
                "verbose_name": "项目管理",
                "verbose_name_plural": "项目管理",
            },
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "managed": True,
                "verbose_name": "资源管理",
                "verbose_name_plural": "资源管理",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "managed": True,
                "verbose_name": "角色管理",
                "verbose_name_plural": "角色管理",
            },
        ),
        migrations.AlterModelOptions(
            name="users",
            options={
                "managed": True,
                "verbose_name": "用户管理",
                "verbose_name_plural": "用户管理",
            },
        ),
        migrations.AlterModelTable(
            name="application",
            table="apps_application",
        ),
        migrations.AlterModelTable(
            name="project",
            table="apps_project",
        ),
        migrations.AlterModelTable(
            name="resource",
            table="apps_resource",
        ),
        migrations.AlterModelTable(
            name="role",
            table="apps_roles",
        ),
        migrations.AlterModelTable(
            name="users",
            table="apps_users",
        ),
    ]
