# Generated by Django 4.1.13 on 2024-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_remove_project_members_remove_role_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(blank=True, max_length=11, verbose_name="手机号"),
        ),
    ]
