# Generated by Django 4.1.13 on 2024-03-22 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_users_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectrolesusers",
            options={
                "managed": True,
                "verbose_name": "项目角色管理",
                "verbose_name_plural": "项目角色管理",
            },
        ),
        migrations.AddField(
            model_name="projectrolesusers",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectrolesusers",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
