# Generated by Django 4.1.13 on 2024-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_alter_resource_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="deploy_type",
            field=models.IntegerField(
                choices=[(0, "虚拟机"), (1, "容器")], default=0, verbose_name="部署类型"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="webhook",
            field=models.CharField(blank=True, max_length=255, verbose_name="Webhook"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.IntegerField(
                choices=[(1, "服务器"), (2, "数据库"), (3, "VPN")],
                default=1,
                verbose_name="资源类型",
            ),
        ),
    ]
