# Generated by Django 4.1.13 on 2024-03-23 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mirage.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_application_deploy_type_application_webhook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.IntegerField(
                choices=[(1, "服务器"), (2, "数据库"), (3, "VPN"), (4, "中间件")],
                default=1,
                verbose_name="资源类型",
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=200, verbose_name="账号名称")),
                (
                    "account_password",
                    mirage.fields.EncryptedCharField(
                        max_length=300, verbose_name="账号密码"
                    ),
                ),
                (
                    "account_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "服务器"), (2, "数据库"), (3, "VPN"), (4, "中间件")],
                        null=True,
                        verbose_name="账号类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="账号描述")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_application",
                        to="apps.application",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_resource",
                        to="apps.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号管理",
                "verbose_name_plural": "账号管理",
                "db_table": "apps_account",
                "managed": True,
            },
        ),
    ]
